spring.application.name=Hanki Backend

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://localhost:5433/hanki
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Spring properties
server.servlet.context-path=/hanki
server.error.include-stacktrace=never

# JWT properties
jwt.secretKey=8ZOl6HG4aHiNRbe1l-b_mLTcOXHmVHUPj5SqfS3T1qE
jwt.accessTokenExpirationMins=30
jwt.refreshTokenExpirationDays=7

