name: PR Checks for Spring Boot (Gradle)

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and Verify Compilation
        run: ./gradlew build --no-daemon --stacktrace

      - name: Run Tests
        run: ./gradlew test --no-daemon --stacktrace
